
#强烈注意：Spring Boot 2.X 版本不再支持配置继承，多数据源的话每个数据源的所有配置都需要单独配置，否则配置不会生效

spring:
  datasource:
    #--------------------------多数据源之一mysql-----------------------------
    mysql:
      type: com.alibaba.druid.pool.DruidDataSource  #表明使用Druid连接池，springboot自带的连接池是HikariCP，所以在配置数据库连接池的时候一定要指定type
      driver-class-name: com.mysql.cj.jdbc.Driver   #m数据库驱动，其实Druid可以根据URL自动识别驱动
      url: jdbc:mysql://192.168.101.62:3306/mysql?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: Cvicse#2020

      initial-size: 5     #初始化时建立物理连接的个数
      min-idle: 5         #最小连接池数量
      max-active: 20      #最大连接池数量
      max-wait: 60000     #获取连接时最大等待时间，单位毫秒
      pool-prepared-statements: true  #是否缓存preparedStatement，也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle；在mysql下建议关闭
      #max-pool-prepared-statement-per-connection-size: #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true；在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-open-prepared-statements: -1
      #validation-query:   #验证查询的SQL，用来检测连接是否有效的sql 必须是一个查询语句
      #test-while-idle: true
      #validation-query-timeout:
      #test-on-borrow: false  #申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      #test-on-return: false  #归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      time-between-eviction-runs-millis: 60000  #配置检测可以关闭的空闲连接间隔时间，单位是毫秒
      min-evictable-idle-time-millis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 400000    #配置一个连接在池中最大生存的时间，单位是毫秒

      filters: stat,wall  #stat：监控统计；log4j：日志；wall：防御sql注入
      aop-patterns: com.web.springbootdruid.service.*   #配置_Druid和Spring关联监控配置，Spring监控AOP切入点，如x.y.z.service.*，配置多个英文逗号分隔
      use-global-data-source-stat: true #合并多个DruidDataSource的监控数据
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录

      web-stat-filter:
        enabled: true   #是否启用StatFilter默认值true
        url-pattern: /* #添加过滤规则
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #忽略过滤的格式
        #session-stat-enable:
        #session-stat-max-count:
        #principal-session-name:
        #principal-cookie-name:
        #profile-enable:

      stat-view-servlet:
        enabled: true           #是否启用StatViewServlet默认值true
        url-pattern: /druid/*   #访问路径为/druid时，跳转到StatViewServlet
        reset-enable: false     #是否能够重置数据
        login-username: druid   #需要账号密码才能访问控制台，默认为root
        login-password: druid
        allow: "127:0:0:1"      #IP白名单
        deny:                   #IP黑名单（共同存在时，deny优先于allow）


    #--------------------------多数据源之二oracle-----------------------------
    oracle:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@192.168.101.62:1521:dgpp
      username: cmvsiac
      password: cvicsemsa
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      #max-pool-prepared-statement-per-connection-size:
      max-open-prepared-statements: -1
      #validation-query:
      #test-while-idle: true
      #validation-query-timeout:
      #test-on-borrow: false
      #test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 400000
      filters: stat,wall
      aop-patterns: com.web.springbootdruid.service.*
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        #session-stat-enable:
        #session-stat-max-count:
        #principal-session-name:
        #principal-cookie-name:
        #profile-enable:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
        allow: "127:0:0:1"
        deny:

    #--------------------------多数据源之三postgres-----------------------------
    postgres:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.100.5:5432/postgres
      username: postgres
      password: postgres
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      #max-pool-prepared-statement-per-connection-size:
      max-open-prepared-statements: -1
      #validation-query:
      #test-while-idle: true
      #validation-query-timeout:
      #test-on-borrow: false
      #test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 400000
      filters: stat,wall
      aop-patterns: com.web.springbootdruid.service.*
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        #session-stat-enable:
        #session-stat-max-count:
        #principal-session-name:
        #principal-cookie-name:
        #profile-enable:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
        allow: "127:0:0:1"
        deny: